{
 "title": "Red Hat Gallery Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Kubernetes namespace", "query": "gallery" }
  ]
 },
 "panels": [
  {
   "title": "Placed Orders Total",
   "type": "stat",
   "description": "Total number of placed orders.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (grpc_io_server_completed_rpcs{namespace=\"$namespace\",service=\"checkoutservice\",grpc_server_method=\"hipstershop.CheckoutService/PlaceOrder\",grpc_server_status=\"OK\"}), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")"
    }
   ]
  },
  { "title": "Frontend Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Server Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(opencensus_io_http_server_request_count_by_method{namespace=\"$namespace\",service=\"frontend\"}[2m]))",
     "legendFormat": "Request {{ http_method }}"
    },
    {
     "expr": "sum without (instance, pod) (rate(opencensus_io_http_server_response_count_by_status_code{namespace=\"$namespace\",service=\"frontend\"}[2m]))",
     "legendFormat": "Response HTTP {{ http_status }}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum  without (instance, pod) (rate(opencensus_io_http_server_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum  without (instance, pod) (rate(opencensus_io_http_server_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum  without (instance, pod) (rate(opencensus_io_http_server_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Client Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (rate(grpc_io_client_completed_rpcs{namespace=\"$namespace\",service=\"frontend\"}[2m])), \"grpc_client_method_short\", \"$1\", \"grpc_client_method\", \".*\\\\.(.*)\")",
     "legendFormat": "{{ grpc_client_method_short }} {{ grpc_client_status }}"
    }
   ]
  },
  {
   "title": "Client Roundtrip Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.75, sum  without (instance, pod) (rate(grpc_io_client_roundtrip_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m]))), \"grpc_client_method_short\", \"$1\", \"grpc_client_method\", \".*\\\\.(.*)\")",
     "legendFormat": "{{ grpc_client_method_short }}  P75"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum  without (instance, pod) (rate(grpc_io_client_roundtrip_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m]))), \"grpc_client_method_short\", \"$1\", \"grpc_client_method\", \".*\\\\.(.*)\")",
     "legendFormat": "{{ grpc_client_method_short }} P90"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum  without (instance, pod) (rate(grpc_io_client_roundtrip_latency_bucket{namespace=\"$namespace\",service=\"frontend\"}[2m]))), \"grpc_client_method_short\", \"$1\", \"grpc_client_method\", \".*\\\\.(.*)\")",
     "legendFormat": "{{ grpc_client_method_short }} P99"
    }
   ]
  },
  { "title": "ProductCatalog Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Server Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (rate(grpc_io_server_completed_rpcs{namespace=\"$namespace\",service=\"productcatalogservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m])), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.75, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"productcatalogservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P75"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"productcatalogservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P90"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"productcatalogservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P99"
    }
   ]
  },
  { "title": "Ad Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Server Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (rate(grpc_io_server_completed_rpcs_total{namespace=\"$namespace\",service=\"adservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m])), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.75, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"adservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P75"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"adservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P90"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"adservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P99"
    }
   ]
  },
  { "title": "Checkout Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Server Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (rate(grpc_io_server_completed_rpcs{namespace=\"$namespace\",service=\"checkoutservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m])), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.75, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"checkoutservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P75"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"checkoutservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P90"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"checkoutservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P99"
    }
   ]
  },
  { "title": "Shipping Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Server Traffic & Errors",
   "type": "graph",
   "description": "The number of requests being made and the rate of failing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum without (instance, pod) (rate(grpc_io_server_completed_rpcs{namespace=\"$namespace\",service=\"shippingservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m])), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }}"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "graph",
   "description": "The time required to serve a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.75, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"shippingservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P75"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"shippingservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P90"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum  without (instance, pod) (rate(grpc_io_server_server_latency_bucket{namespace=\"$namespace\",service=\"shippingservice\",grpc_server_method!=\"grpc.health.v1.Health/Check\"}[2m]))), \"grpc_server_method_short\", \"$1\", \"grpc_server_method\", \".*/(.*)\")",
     "legendFormat": "{{ grpc_server_method_short }} {{ grpc_server_status }} P99"
    }
   ]
  }
 ]
}