apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: gallery
spec:
  allInOne:
    options:
      log-level: info
  strategy: allInOne
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: jaeger-collector
  namespace: gallery
spec:
  host: jaeger-collector
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jaeger
  namespace: gallery
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      app: jaeger
  policyTypes:
  - Ingress
